### ISSUE TITLE
Multilinguality

### ISSUE THREAD

**Issue by botsarefuture** [botsarefuture/mielenosoitukset_fi#115]

**Comment by botsarefuture** [comment]
Now we use transifex for making the translations!

**Comment by botsarefuture** [comment]
@samimaat is this the proper way to handle `aria-label`, or should we wrap it in `{{ _('Etsi käyttäjiä') }}` first?

Basically:
- Is it better for aria label to be in English or for it to be in their native language?

https://github.com/botsarefuture/mielenosoitukset_fi/blob/1bb68f537930cac4bf934744f229695a7dca9af3/templates/admin/user/list.html#L92-L93

**Comment by samimaat** [comment]
If I understood correctly that you simply want to translate the input field to English, then you should translate the `<label>` element's content and the `placeholder` attribute's content.

`aria-label` isn't needed when it's done this way. In its current implementation it mixes Finnish and English, which would be confusing either way.
